name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: myapp:latest
  CONTAINER_NAME: myapp
  HOST_PORT: 3000
  CONTAINER_PORT: 3000

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Run container
        run: |
          docker run -d --name $CONTAINER_NAME -p $HOST_PORT:$CONTAINER_PORT $IMAGE_NAME
          sleep 10  # give time for container to start

      - name: Show running containers
        run: docker ps -a

      - name: Show container logs
        run: docker logs $CONTAINER_NAME

      - name: Stop and remove container
        run: docker rm -f $CONTAINER_NAME || true
